### ISSUE TITLE
Removing robustness of the app - chief

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10390]
### Discussed in https://github.com/kodadot/nft-gallery/discussions/10370

<div type='discussions-op-text'>

<sup>Originally posted by **exezbcz** May 29, 2024</sup>
More and more, I am thinking about removing the complexity and unused parts of the app. This discussion is made to choose the parts of apps that we will remove and comment out. 

## My picks
- create
- settings
- notifications
- explore card - remove networks etc. 
- explore? and make it more landing page exploration 
- on-chain identity
- featured articles - replace with some educative articles 
- modal flows - free mint, other complex stuff 

curious what you think</div>

# Todo 

- [x] https://github.com/kodadot/nft-gallery/issues/10427
- [x] https://github.com/kodadot/nft-gallery/issues/10389
- [x] #10428
- [ ] explore - q2/q3 - gradually move exploration to landing page
- [x] https://github.com/kodadot/nft-gallery/issues/10425
- [x] https://github.com/kodadot/nft-gallery/issues/10426
- [ ] https://github.com/kodadot/nft-gallery/issues/10400
- [x] https://github.com/kodadot/nft-gallery/issues/10394

**Comment by exezbcz** [comment]
move to: 
- https://github.com/kodadot/nft-gallery/issues/10400
