### ISSUE TITLE
Tracking issue for the KodaDot Statemine

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1453]
- [x] after the collection is created, it doesn't show me that in a notification 
- [x] when I go to mint and NFT and I got to choose I collection, I don't see the name of the collection instead, I see numbers (b42849f0d58fda79c5fc16ca4288ef4c9ccdc5f2)
- [x] broken route from profile -> collections to collection detail (b9c9a715e5833b828bd36b5d95bbd63cdecb4038)

ht/ @onerawartist

**Comment by onerawartist** [comment]
when i minted an nft , the page didn't refresh and take me to the nft page, nothing happened but the nft was indeed minted

![WM nft 01](https://user-images.githubusercontent.com/71472224/145401281-d79eeaa1-6c99-4cdd-a09b-f0d7e24e3f47.png)
![WM nft 02](https://user-images.githubusercontent.com/71472224/145401338-36b6076d-6615-4ea2-9ed4-41d1cb33d109.png)

**Comment by onerawartist** [comment]
when i go to profile , then i click on collections ,then i click on one of the collections , i supposed to see " the collection profile " , instead i get the "nft" type of page

![wm03](https://user-images.githubusercontent.com/71472224/145401477-5d25cf17-cdf0-4e73-afaa-9a83fbcb4eba.png)

this happens when the collection is still empty

**Comment by onerawartist** [comment]
my collections has names , but when i go to mint and nft and i got to choose i collection , i don't see the name of the collection , instead i see numbers ,

![wm01](https://user-images.githubusercontent.com/71472224/145401675-4d778b71-28c0-471b-9528-9afad8e427b2.png)

**Comment by yangwao** [comment]
@vikiival can we close this?
