### ISSUE TITLE
User preferences v2  -- followup features

### ISSUE THREAD

**Issue by kkukelka** [kodadot/nft-gallery#1581]
Once we've merged #1569 we've scarapped the following issues to new user preference tab:

- [ ] Grayscale & Monochrome option #1370
- [ ] Borders, shadow and gap #2177
- [ ] Ability to change colours in user preferences #1638 

### This should go to the v3 follow up
- [ ] Choose your indexer #1420
- [ ] Fast-checkout from history screen into user preferences #1493
- [ ] user based deny list #1177 
- [ ] see only unique NFTs #1649

### Done
- [x] Add recent searches to input field #1294
- [x] GalleryItem description wrapper #1475
- [x] pick what wasn't made referred to #1160 
- [x] Add YOLO to user preference #1417

some of these issues still need to be resolved first 🌮

**Comment by yangwao** [comment]
I've just checked @kkukelka it's good to go, the chief (parent) label is added and looking forward to the next batch of user preferences! ;)
