### ISSUE TITLE
Milestone 2 - Add XR support for 3D NFTs and scenes

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#165]
# How it started
Part of our milestone2 would be adding XR support. We are eyeing go with a-frame for now and model-viewer. 
Our initial work could be found here https://kusama.polkassembly.io/post/384 

[Recent version of M2 proposal](https://docs.google.com/document/d/10LjFxQsOE0XbWosck4RO-8A41fSq5ASXXKrpIw7UM7I/edit#heading=h.jarmlbjrxe4a)

# Vision
The main delivery is a basic WebXR (AR/VR) implementation of assets rendering in themed and customizable metaverses in low-poly mode.
During the summer we did a wild hack and leveraged WebXR framework A-Frame from Mozilla to KodaDot: you can learn more about it here. This was very successful among the wide crypto community.
To continue with this experience, we would like to bring users mobile-first experience of exploring and operating with assets in Extended Reality: You may see demonstration of our wild hacks, which seeded inspiration for an ArtProject AR installation
Moreover, users will be able to set positions of each object in space so they are able to recreate galleries in AR/VR on their own.

# Roadmap Milestone 2
Milestone2 at the time of writing in November 2020 consists, may adjust along the road

- [ ] Research on AR/VR architecture and how assets could be explored in metaverse
- [ ] Create page & components which displays selected NFTs in AR/VR space by user or address of asset
- [ ] Implement sharable ability through links 
- [ ] Write implementation for showing metadata for particular NFT 
- [ ] Ability to view collection in AR/VR - putting NFT in the 3D space
- [ ] Co-operation with AR/VR experts to get best industry standards in place
- [ ] Possibility to set position of objects in space
- [ ] Release open source library to interact with RMRK on Kusama through AR/VR
- [ ] Documentation of open source library
- [ ] Support for common VR headsets like Oculus Quest (2) and AR headsets like nReal or Magic Leap

## We aim to supported these formats
- [x] glb - model-viewer should work with this and aframe
- [ ] gltf - model-viewer should work with this and aframe
- [ ] usdz - [vectary supports that](https://www.vectary.com/)
- [ ] obj
- [ ] others prior research
- [ ] ~fbx~ - probably not as it's owned by Autodesk 

## Create models

- [vectary.com](vectary.com)
- [Blender](https://www.blender.org/)
- ???
### Misc
Google low poly is closing, [alternatives](https://educatorsinvr.com/2021/01/03/google-poly-low-poly-alternatives/)
