### ISSUE TITLE
After minting the NFT token, redirect creator to the minted NFT, make user first crawler for IPFS

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#184]
We encounter problems with first mints, that crawlers (Telegram, Twitter, Facebook, Instagram) which fetch it for social media OGs, gets an undefined response because timed out on fetch request.

The thing here would be **warm IPFS gateways with mints before users gonna post it on social media, so social media crawlers fetch pictures.**

After successful mint open nft detail and **fetch on background headers of multimédia through IPFS gateways (you can see them in gallery item detail)**

If there are more, open collection so the user can share it

As we would like to embrace the flow of sharing, would be nice to redirect them to the art.

### Task
- [x] open hash on other gateways to warm up IPFS catch before sharing -- if you do it on background, would be much better for user than an opening for user lot of tabs
- [x] encourage them with sharing -- highlight sharing buttons? copy it to the clipboard URL?
- [x] you can use the deployed version from PR -- Netlify deploys with every new PR
- [x] post video how it works
- [x] merged from https://github.com/kodadot/nft-gallery/issues/143

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.2268 KSM (99.93 USD @ $440.6/KSM)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/kodadot/nft-gallery/184/100025684).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/kodadot/nft-gallery/184/100025684).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,348,896.88 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [mrubes375](https://gitcoin.co/mrubes375) has started work.**

Will complete all tasks outlined in the issue description.

It sounds like there are two tasks here, can you please confirm?

1) Prefetch link for all gateways supported for an NFT when users click on an NFT details page from the gallery view.
2) Revamp the sharing UI.  (Should the copy functionality replace the window that opens allowing users to post the NFT to social media)

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/kodadot/nft-gallery/184/100025684).

**Comment by yangwao** [comment]
Took Q from gitcoin as I can't reply to @mrubes375
> Will complete all tasks outlined in the issue description.
>It sounds like there are two tasks here, can you please confirm?
> 1) Prefetch link for all gateways supported for an NFT when users click on an NFT details page from the gallery view.

Yes, this is more important for us is a pain in the ass that while you mint stuff, won't show in crawlers because they hit gateway where it apparently isn't.. yet replicated. 

> 2) Revamp the sharing UI. (Should the copy functionality replace the window that opens allowing users to post the NFT to social media)

We meanwhile have redesign sharing buttons, something which nudges the user to share it would be awesome I guess

**Comment by dmxdev4** [comment]
@yangwao  Hi could give more details about "mint stuff" and the crawlers and the gateway thanks

**Comment by XyloDrone** [comment]
Add easy sharing option once the user is redirected to their work. Sharing options in drop down, image 2: 
![Screenshot 2021-05-18 at 23 57 37](https://user-images.githubusercontent.com/84407059/118733879-1cbf2b00-b835-11eb-9268-4f0a5f1bdbc9.png)

![Screenshot 2021-05-18 at 23 59 51](https://user-images.githubusercontent.com/84407059/118733911-29dc1a00-b835-11eb-8d03-e7c56258aa31.png)

**Comment by yangwao** [comment]
> @yangwao Hi could you give more details about "mint stuff" and the crawlers and the gateway thanks
What do you mean "mint stuff" ?

Speaking of crawlers would be great to fetch header from pinata might does the job, it's experimental issue and up to you to find out :)
You can use on telegram @WebpageBot or for twitter https://cards-dev.twitter.com/validator

**Comment by vikiival** [comment]
Maybe solved in #513

**Comment by yangwao** [comment]
yup let's close it, I guess hope it works
