### ISSUE TITLE
⛱️  umbrella issue for profiles & create profiles for artists 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#226]
We would like to make it easy for the non-tech-savvy audience to onboard to Kodadot. 
Simple as that.

- [ ] onboarding to create profile - #16 
- [ ] https://github.com/kodadot/nft-gallery/issues/524
- [ ] show liked NFTs by user - #221 
- [x] flex UX - #225 
- [x] show on-chain data in users profile - #134
- [x] creators list - literally list of profiles - #157

**Comment by yangwao** [comment]
lol found archive @XyloDrone

**Comment by exezbcz** [comment]
nice, 2021

**Comment by JustLuuuu** [comment]
> nice, 2021

next time close it directly :D
