### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#23]
I've made a list of how it's going, then made a full report once we are done here.

- ✅ Leveraging existing KodaDot components using Vue.js

- ✅ Research on architecture components to ensure versatility for other projects

 - ✅ Create a set of components that allows to read and display RMRK NFT of multiple artwork types 

   - ✅  image
   - ✅ gif
   - ✅ audio 
   - ✅ video 
   - ✅ text

- ✅ Extend RMRK standard to support appreciations (web 2.0 likes) and comments for NFT

- ✅ Display metadata for particular NFT

- ✅ Able to transfer and mint RMRK NFT

- ✅ Ability to create RMRK collection 

- ✅ Integration with Pinata SDK for pinning assets from local filesystem
- ✅ Researching to use Textile Buckets or Threads, implement it if it’s feasible
- ✅ Release open-source library to interact with RMRK on Kusama
- [x] Possibility to create a collection of NFTs (lists on Twitter) and create decentralized links to share it with others #37 
- [x] Deploy separate web pages (which could be deployed to IPFS as well) which would be embeddable  into other existing web applications using <iframe/> which would work as a page generator to show particular collections or by addresses. #36 
- [x] Write introduction article around experience with development around RMRK NFT implementation
- [x] Documentation of open source library & how to embed these for their galleries

**Comment by vikiival** [comment]
[Article](https://medium.com/kodadot/traverse-to-the-prime-show-733d6046d3f5)

**Comment by yangwao** [comment]
Well, it's wrap apparently! Move to M1.5!
