### ISSUE TITLE
Seo upgrade 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#243]
# Tasks to do 

- [ ] generate sitemap.xml on build from list to include application pages
  - [ ] rmrk/rare
  - [ ] rmrk/gallery
  - [ ] rmrk/mint
  - [ ] rmrk/create
  - [ ] rmrk/credit
  - [ ] FAQ
  - [ ] Settings
  - [x] Carbonless - define og:description and og:title
  - [ ] Sustainability - define og:description and og:title
- [ ] tune seo description for NFTs to reflect 
  - [x] put nft token name in title
  - [x] description of NFT to the description of page
  - [x] fill og:author with creator address
- [ ] deliver screenshots 
  - [ ] preview how it looks like for indexed sitemap
  - [ ] preview of NFT detail 
- [ ] post link tools you used to test your seo
https://www.google.com/search?q=site%3Anft.kodadot.xyz

https://user-images.githubusercontent.com/5887929/112744027-ab819b00-8f9c-11eb-9bc7-566e9638c7ea.mp4

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.3775 KSM (150.63 USD @ $399.01/KSM)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/kodadot/nft-gallery/243/100025705).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/kodadot/nft-gallery/243/100025705).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,485,346.74 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [florian911](https://gitcoin.co/florian911) has started work.**

Yesresponse will be reflected in a comment on the Github issue.)

 
Yes

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/kodadot/nft-gallery/243/100025705).

**Comment by yangwao** [comment]
@florian911 is there any way how I can help you? :)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 5 months from now.
Please review their action plans below:


**1) [andreygrin](https://gitcoin.co/andreygrin) has started work.**

Will provide PR by end of the week with related updates

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/kodadot/nft-gallery/243/100025705).

**Comment by yangwao** [comment]
It's done in #409

**Comment by yangwao** [comment]
@gitcoinbot help

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 0.3775 KSM  (106.61 USD @ $280.55/KSM) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,691,100.19 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by yangwao** [comment]
@gitcoinbot  have bug so I had to pay out other way around https://kusama.subscan.io/extrinsic/7671349-3

Reported - https://github.com/gitcoinco/web/issues/8968
