### ISSUE TITLE
Towards Vue 3 / Nuxt 3 migration roadmap

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2690]
# [Migration Roadmap click here](https://github.com/kodadot/nft-gallery/issues/2690#issuecomment-1525341446)

---

### Is your feature request related to a problem?

Since we have Nuxt Bridge 
- #2677 

### we should leverage the latest features

- [Pinia](https://pinia.vuejs.org/) could be considered (#4755)
- Composition API (#4750)
- <s>blocker https://github.com/kodadot/nft-gallery/issues/2692</s>
- #2081 
- [@nuxtjs/apollo](https://apollo.nuxtjs.org/getting-started/quick-start) next
- [@nuxtjs/i18n](https://v8.i18n.nuxtjs.org/getting-started/setup) #3916 

[Nuxt 3 Docs](https://v3.nuxtjs.org/docs/usage/data-fetching)
[Nuxt Bridge](https://v3.nuxtjs.org/getting-started/bridge/)
[Those looking for chart](https://v3.nuxtjs.org/getting-started/introduction/)

## Ref
- https://github.com/kodadot/nft-gallery/issues/4704

**Comment by yangwao** [comment]
Putting p5 as major release nuxt/vite by all hands call will be in June so it's not a hurry nor we are not gaining any edge having it.

**Comment by preschian** [comment]
library/tools recommended for vue3: https://v3-migration.vuejs.org/recommendations.html#new-framework-level-recommendations

- New versions of Router, Devtools & test utils w/ Vue 3 support
- Build Toolchain: Vue CLI -> [Vite](https://vitejs.dev/)
- State Management: Vuex -> [Pinia](https://pinia.vuejs.org/)
- IDE Support: Vetur -> [Volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar)
- New command line TypeScript support: [vue-tsc](https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc)
- SSG: VuePress -> [VitePress](https://vitepress.vuejs.org/)
- JSX: @vue/babel-preset-jsx -> [@vue/babel-plugin-jsx](https://github.com/vuejs/jsx-next)

**Comment by vikiival** [comment]
> IDE Support: Vetur -> [Volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar)

I already switched to Volar

**Comment by preschian** [comment]
Some notes to help us migrate to vue3/nuxt3:

We need to reduce using `nuxt-property-decorator` first and use composition API instead. It will help us to migrate to vue3/nuxt3
https://github.com/nuxt-community/nuxt-property-decorator/issues/83#issuecomment-1245139696. at least for newer components
related: https://github.com/kodadot/nft-gallery/issues/2893

And I think we face this problem also https://github.com/nuxt-community/nuxt-property-decorator/issues/83#issuecomment-1246615441; most of the library is still not ready in nuxt3. And maybe some libs/modules are not compatible also in nuxt-bridge

**Comment by kkukelka** [comment]
@preschian 
just as a sidenote:
afaik Class API is not going to be supported in Vue3/Nuxt3 whatsoever. So we are kind of forced to rewrite everything to Composition API/Options API before we can upgrade to Nuxt3

**Comment by vikiival** [comment]
> So we are kind of forced to rewrite everything to Composition API/Options API before we can upgrade to Nuxt3

![Uploading Screenshot 2022-10-17 at 15.43.08.png…]()

**Comment by yangwao** [comment]
> reduce using `nuxt-property-decorator`

- #4750 

What's about libraries? @preschian

**Comment by yangwao** [comment]
> * nuxt-buefy

what's issue with nuxt-buefy? jtommy (buefy author) can help us push things and happy to pay/sponsor repo as I bet we will be not only one stuck here. If you can get back to me with issue what's there we can put spotlight on that to remove one blocker
- https://github.com/buefy/nuxt-buefy/issues

**Comment by roiLeo** [comment]
> several days ago I'm trying to upgrade to nuxt3, but still got blocked by these modules

Did you manage to build anything?

>     * nuxt-buefy

This one IMO won't update in the upcoming month, we can try to wrap buefy config & import each components or replace buefy code with oruga-ui.
it may help rewritte some of the components If we can list what is still being used.

>     * @nuxtjs/apollo

[@nuxtjs/apollo](https://apollo.nuxtjs.org/getting-started/quick-start) next

>     * @nuxtjs/i18n

i18n v8 is in [beta](https://v8.i18n.nuxtjs.org/getting-started/setup)

**Comment by roiLeo** [comment]
> I think this is the goal.

608 results in 149 files 👯‍♀️

**Comment by roiLeo** [comment]
What need to be done:
- [ ] finish #4755, remove vuex & vuex-persist (&patch)
- [ ] replace all buefy components with `Neo` lib or oruga and remove buefy
- [ ] complete #4750 
- [ ] Audit Vue3 compatibility with some packages (tippy, infinite-loading, markdown-render)
- [ ] replace Identicon implementation for Vue3 (ping me)
- [ ] upgrade to nuxt3, remove nuxt-bridge & edge
- [ ] upgrade [i18](https://v8.i18n.nuxtjs.org/getting-started/setup) #3916
- [ ] upgrade [@nuxtjs/apollo](https://apollo.nuxtjs.org/getting-started/quick-start)
- [ ] upgrade nuxt3 plugins
- [ ] update layouts & page with vue3 composition (  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>

**Comment by vikiival** [comment]
> replace Identicon implementation for Vue3 (ping me)

The polkadot package should be usable for Vue3 too

**Comment by roiLeo** [comment]
> The polkadot package should be usable for Vue3 too

https://github.com/polkadot-js/ui/issues/747 
&
https://stackblitz.com/edit/vue3-vite-starter-efpvnz?file=src%2FApp.vue,src%2Fcomponents%2FHelloWorld.vue

**Comment by stephenjason89** [comment]
> 



> > several days ago I'm trying to upgrade to nuxt3, but still got blocked by these modules
> 
> Did you manage to build anything?
> 
> > nuxt-buefy
> 
> This one IMO won't update in the upcoming month, we can try to wrap buefy config & import each components or replace buefy code with oruga-ui. it may help rewritte some of the components If we can list what is still being used.
> 
> > @nuxtjs/apollo
> 
> [@nuxtjs/apollo](https://apollo.nuxtjs.org/getting-started/quick-start) next
> 
> > @nuxtjs/i18n
> 
> i18n v8 is in [beta](https://v8.i18n.nuxtjs.org/getting-started/setup)

Hello @roiLeo What's the issue you encounter with @nuxtjs/apollo?

**Comment by roiLeo** [comment]
> Hello @roiLeo What's the issue you encounter with @nuxtjs/apollo?

I didn't encounter issue yet, we need to fix #4750 first.

**Comment by yangwao** [comment]
Continue to 
- https://github.com/kodadot/nft-gallery/issues/7034
