### ISSUE TITLE
Roadmap to KodaBot-as-a-service

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3091]
After talks with @yangwao and @vikiival, we'd like to see KodaBot evolve into a project/repo agnostic service provided for any project within the dotsama ecosystem. We want to get support from the treasury to do this properly. This roadmap will help me get the project to the (hopefully) accepted proposal. 

Timespan:  **June - July 2022**

0. KodaBot at dev.to, part 1 ⇾ assign part

- [x] describe the assigning process for devs and the public to understand
- [x] publish ⇾ 31.05.2022
- [x] #3010 

1. KodaBot update 1:
**cleanup + automatization**

- [ ] closed/merged PR endpoint - save only pull number ⇾ wait for 10 PRs to accumulate
- [ ] check every day at 12am, if mergedPrs > 10
- [ ] run updating of leaderboard/burnrate/reviews/issues tables if mergedPrs > 10
- [ ] run updating of the amounts by subscan API /w provided addresses file stored on CF
- [ ] switch from using Autocode's KV storage to full CF operation (integrate automatic creation of issues namespace in case it doesn't exist (rubick, docs, etc.))

2. KodaBot at dev.to, part 2 ⇾ analytics part

- [ ] write a supplementary article on how are we producing analytics around the project /w KodaBot
- [ ] publish -> 14.06.2022

3. KodaBot update 2:
**refact000r,  payout integration, more repo-agnostic approach**

- [ ] integrating payout part (currently running on @yangwao autocode) into KodaBot
- [ ] moving settings from .js file into JSON stored on Cloudflare (prep. for outside use of KodaBot)
- [ ] refactoring the code into a mature piece of software (as mature as possible), throw out unused code
- [ ] final commit to github.com/petersopko/kodabot repo and fork it to continue development under KodaDot's project (kodabot as new repo)
- [ ] develop GH OAuth at kodadot.xyz/dev to provide the bot with current dev's address instead of repeated addresses fillout at PR template

4. KodaBot at dev.to, part 3 ⇾ payout integration part

- [ ] write another supplementary article describing the payout part of the bot
- [ ] publish -> 28.06.2022

5. Proposal preparation for KodaBot
- [ ] diagram of multiple KodaBot parts
- [ ] vision -> KodaBot as a free service for Kusama native projects
- [ ] one-stop-shop for async development teams -> providing assigning, payouts, and analytics on GH repo as a public good service
- [ ] having this service integrated and provided for people with verified on-chain identity
- [ ] get supplementary graphics for proposal 
- [ ] talk about the project to w3f people
- [ ] figure out the amount

6. Submit the proposal to the treasury
- [ ] write up a summary article about the whole process
- [ ] submit the proposal with 4 linked articles written about KodaBot
- [ ] deadline @ 18.07.2022

**Comment by vikiival** [comment]
> switch from using Autocode's KV storage

Aren't you using CF KV already? 
Maybe you wanted to rewrite the logic from autocode to CF

**Comment by vikiival** [comment]
> robust solution long term.

All I see is RUST 🦀
