### ISSUE TITLE
Basilisk v0.3

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3648]
We will be moving here issues from original parent issue #660, which weren't done in the first phase and will be done in the upcoming phase.

## Tracking Bugs 
- #3756 

## Roadmap 
- More changes related to the current BSX implementation are coming soon:
- [x] https://github.com/kodadot/nft-gallery/issues/3376

### Explorer

- [x] https://github.com/kodadot/nft-gallery/issues/2881

### Offers
- [x] https://github.com/kodadot/nft-gallery/issues/3584
- [x] https://github.com/kodadot/nft-gallery/issues/3583
- [x] https://github.com/kodadot/nft-gallery/issues/3514
- [x] https://github.com/kodadot/nft-gallery/issues/3401
- [ ] https://github.com/kodadot/nft-gallery/issues/766
- [x] https://github.com/kodadot/nft-gallery/issues/3463

### Related Issues
- [ ] https://github.com/kodadot/nft-gallery/issues/3134
- [ ] https://github.com/kodadot/nft-gallery/issues/3138
- [x] https://github.com/kodadot/nft-gallery/issues/3207
- [ ] https://github.com/kodadot/nft-gallery/issues/3350
- [x] https://github.com/kodadot/nft-gallery/issues/3265
- [x] https://github.com/kodadot/nft-gallery/issues/3291
- [x] https://github.com/kodadot/nft-gallery/issues/3294
- [x] https://github.com/kodadot/nft-gallery/issues/3352
- [x] https://github.com/kodadot/nft-gallery/issues/3368
- [x] https://github.com/kodadot/nft-gallery/issues/3362

### Auctions
- [x] https://github.com/kodadot/nft-gallery/issues/2776
- [ ] https://github.com/kodadot/snek/issues/2
