### ISSUE TITLE
Tracking: Identity

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3783]
### Is your feature request related to a problem?

Current implementation of the indentity is so far really bad and therefore I would like to propose a new way of doing/handling identity:

Technical background:
- [ ] Implement multichain @subsquid identity indexer (for Kusama, Basilisk, Moonriver, Acala, Astar).
- [ ] fetch data from indexer instead of connecting to chain - That's why you see hundreds of connection logs on the landing page
- [ ] Cache the data for at least 3 days - indentity does not change much. 

Vue: 
- [ ] rewrite into a smaller pieces (may fixed by #3749)
- [ ] turn off that hover on the phone :)

### Describe the solution you would like

~

Just a 🧠 dump, will process after 🇪🇸 

### Describe alternatives you have considered

~

**Comment by yangwao** [comment]
<img src="https://media3.giphy.com/media/cnvYUsZkczj04Kpk3y/giphy.gif"/>
