### ISSUE TITLE
Redesign: Leftovers from pre-Neobrutalism

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3956]
This issue should track leftovers from:
- kodadot/nft-gallery#1619 

I've spent some time going through the issues mentioned there and two things are clear:
1. We are going into different direction with style
2. Many of the issues are not getting touched by anybody anymore

Anyways, let's track what was left from the previous iteration here, perhaps we'll come back to it later.

My goal is to remove the redundant issues, some things were implemented and there are still issues open for them. We're currently at 620 open issues and maybe the top 100 gets recycled (we're solving mainly the new ones -> I'll produce table for this soon)

## Leftovers

**Personal account zone: My Profile**

- [ ] kodadot/ideas#15 
- [x] kodadot/nft-gallery#1432 
- [x] kodadot/nft-gallery#1526 
- [x] kodadot/nft-gallery#1516
- [ ] kodadot/grants#19 

**Landing**

- [x] kodadot/nft-gallery#90 
- [ ] kodadot/ideas#7 
- [x] kodadot/nft-gallery#1489 
- [x] kodadot/nft-gallery#1445 
- [x] kodadot/nft-gallery#1564 

**Gallery+Search Engine**

- [ ] kodadot/nft-gallery#348 
- [x] kodadot/nft-gallery#859 
- [ ] kodadot/ideas#8
- [x] kodadot/nft-gallery#903 
- [x] kodadot/nft-gallery#285
- [x] kodadot/nft-gallery#1023 
- [x] kodadot/nft-gallery#1088 
- [ ] kodadot/ideas#22 
- [x] kodadot/nft-gallery#1526 
- [x] kodadot/nft-gallery#1174 
- [x] kodadot/nft-gallery#991 

**Create(Minting)**

- [x] kodadot/nft-gallery#378 
- [x] kodadot/nft-gallery#460
- [x] kodadot/nft-gallery#419 
- [x] kodadot/nft-gallery#614 
- [ ] kodadot/ideas#12 
- [x] kodadot/nft-gallery#847 
- [x] kodadot/nft-gallery#614 
- [ ] kodadot/ideas#15 
- [x] kodadot/nft-gallery#991 
- [x] kodadot/nft-gallery#1005 
- [x] kodadot/nft-gallery#1094 
- [x] kodadot/nft-gallery#1330 
- [x] kodadot/nft-gallery#1406 
- [x] kodadot/nft-gallery#1526 
- [x] kodadot/nft-gallery#991 

**NFT + Collection view(I need to separate these accordingly as issues are bundled together at the moment)**

- [x] kodadot/nft-gallery#2746
- [x] kodadot/nft-gallery#219 
- [x] kodadot/nft-gallery#357
- [x] kodadot/nft-gallery#901 
- [x] kodadot/nft-gallery#1330 
- [x] kodadot/nft-gallery#910 
- [ ] kodadot/ideas#19 
- [ ] kodadot/ideas#21 
- [x] kodadot/nft-gallery#1606 
- [x] kodadot/nft-gallery#936 
- [x] kodadot/nft-gallery#1252 
- [x] kodadot/nft-gallery#14 
- [x] kodadot/nft-gallery#1010 
- [ ] kodadot/ideas#22 
- [x] kodadot/nft-gallery#1174 
- [x] kodadot/nft-gallery#878 
- [x] kodadot/nft-gallery#1323 
- [x] kodadot/nft-gallery#1423 
- [x] kodadot/nft-gallery#1012 
- [x] kodadot/nft-gallery#1483 
- [ ] kodadot/ideas#7 
- [x] kodadot/nft-gallery#1122 
- [x] kodadot/nft-gallery#991 
- [ ] kodadot/ideas#40 
- [ ] kodadot/nft-gallery#348 

**Help: FAQ+Tutorials**

- [x] kodadot/nft-gallery#847 
- [x] kodadot/nft-gallery#614 
- [x] kodadot/nft-gallery#725 
- [x] kodadot/nft-gallery#915

**Comment by vikiival** [comment]
@exezbcz are there any fancy ideas worth having?
