### ISSUE TITLE
redesign: GalleryItem MISC leftover

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#4354]
## TODO:

- [x] fix font-awesome integration in histoire (#4782)
- [x] create NeoDropdown component based on o-dropdown in histoire (#4361)
- [x] NeoButton font familly in histoire (done in #4376)
- [x] NeoButton scss file?
- [ ] Small issue `history/getCurrentlyViewedItem` not updating
- [ ] border on arrow tooltip (https://github.com/kodadot/nft-gallery/issues/4354#issuecomment-1342719002)

*from https://github.com/kodadot/nft-gallery/pull/4330#issue-1449399696*

**Comment by daiagi** [comment]
@roiLeo 
I'd like to create the NeoDropdown. may I?

**Comment by roiLeo** [comment]
> @roiLeo I'd like to create the NeoDropdown. may I?

Sure! it's very good for a start with histoire

**Comment by roiLeo** [comment]
### note for later
- [ ] fix page title on redesigned page

**Comment by exezbcz** [comment]
> activity tab:
> 
> * [ ]  [feat: activity tabs #4411 (comment)](https://github.com/kodadot/nft-gallery/pull/4411#issuecomment-1345302911)
> 
> ```
> Current issues are 
> - user doesn't know which tab is currently selected -- bold text issues, we may change to different font?
> - currently there are missing wrapping text, we can use `...` ? For addresses I would like to use some filter function with 3 beginning letters and 3 ending letters for now? Like `2Xk...9oP`
> - hover card should pop up under cursor. Now position is showing over whole table
> - events name should not be in capslock, only capital letter on event
> - on the time column we probably can strip "about" if there is "about 1 month ago"  
> - link between tabs and column names should be k-white? 
> ![image](https://user-images.githubusercontent.com/5887929/206864983-77032c8b-494b-4247-a400-11828d643cff.png)
> - responsive issues but can be solved separately, we will came up with design 
> ```


yup, i have one change about the filters, i would create seperate issue for that and i will maybe include the feedback into it

**Comment by yangwao** [comment]
is this still on map?

**Comment by roiLeo** [comment]
closing this one as partially completed
