### ISSUE TITLE
Refactor: Nuxt3 plugins

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#5314]
> All plugins in your `plugins/` directory are auto-registered, so you should not add them to your `nuxt.config`

> .client suffix in the file name to load a plugin only on the client side.

```ts
export default defineNuxtPlugin(nuxtApp => {
  // Doing something with nuxtApp
})
```
### Done
- [x] vue-gtag
- [x] consola
- [x] infiniteScroll (#5329)
- [x] vuex-persist (#5251)
- [x] filters
- [x] icons
- [x] userBalance (???)
- [x] assets (???)
- [x] keyboardEvents
- [x] polkadot
- [x] vueTippy
- [x] globalVariables
- [x] endpoint
- [x] vueClipBoard => [useClipboard](https://vueuse.org/core/useClipboard/) #7229
- [x] vueSocialSharing (#7233)
- [x] vueAudioVisual (#5228)
- [x] pwa

### Todo

- [ ] sentry => BLOCKED no Nuxt3 version
- [ ] seoMetaGenerator => `useHead`
- [ ] https://github.com/kodadot/nft-gallery/issues/5314#issuecomment-1702980325

**Comment by pbkompasz** [comment]
@yangwao I have refactored a couple already. Here is the current status:

 - [ ] endpoint
 - [X]  filters
  - [ ] globalVariables
  - [X] icons
  - [X] keyboardEvents
  - [ ] polkadot
  - [ ] pwa
  - [X] sentry
  - [ ] seoMetaGenerator => useHead
  - [ ] vueAudioVisual (https://github.com/kodadot/nft-gallery/issues/5228)
  - [X] vueClipBoard => [useClipboard](https://vueuse.org/core/useClipboard/)
  - [ ] vueSocialSharing (not workinnng with nuxt3 and new version plugin error)
  - [X] vueTippy
  - [X] vuex-persist (https://github.com/kodadot/nft-gallery/issues/5251)
  
I do have a couple of questions:
1. the `endpoint` plugin is just a simple import, do we need that?
2. `polkadot`, `globalVariables` and `pwa` are already exporting a default function. Should those be also refactored or are they good currently?
3. The plugins are not being auto-registered.

**Comment by roiLeo** [comment]
so far so good, issue is not up to date. most plugins have been fixed.

what's missing:

- [ ] consola 
- [ ] vue-infinite scroll 
- [ ] pwa
- [ ] font-awesome pro version (grid-2 icon etc..)
- [ ] QR code
- [ ] clipboard (#7064)
- [ ] popover
- [ ] download
- [ ] image preview

**Comment by pbkompasz** [comment]
@roiLeo What about notifications. Should that be converted into a plugin? It is used by clipboard and it is commented out in the nuxt branch.

**Comment by roiLeo** [comment]
@pbkompasz ref https://github.com/kodadot/nft-gallery/pull/7083#issuecomment-1702496538, @preschian might takes care of it. But feel free to open PR if you want to fix it asap.
