### ISSUE TITLE
Goodbye Buefy

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#5852]
## Rewrite [Buefy](https://buefy.org/documentation) components in `libs/ui` using [Oruga-ui](https://oruga.io/documentation/)
part of 
- #2690 

#### In Progress
- [x] replace buefy snackbar & toast #6744 

#### Done
- [x] `<b-progress />` => component or check Bulma #5895
- [x] `<b-carousel />` => `<NeoCarousel />` (Oruga [Carousel](https://oruga.io/components/Carousel.html))  #5884
- [x] `<b-carousel-item />` => `<NeoCarouselItem />` #5884
- [x] `<b-icon />` => `<NeoIcon />` #5858
- [x] `<b-modal />` => `<NeoModal />` #5883 
- [x] `<b-datepicker />` => `<NeoDatepicker />` (Oruga [Datepicker](https://oruga.io/components/Datepicker.html)) #5946
- [x] `<b-checkbox />` => `<NeoCheckbox />` #6000 
- [x] `<b-steps />` => `<NeoSteps />` (Oruga [Steps](https://oruga.io/components/Steps.html)) #5917
- [x] `<b-step-item />` => `<NeoStepItem />` #5917
- [x] `<b-switch />` => `<NeoSwitch />` (Oruga [Switch](https://oruga.io/components/Switch.html)) #5945
- [x] `<b-radio-button />` => `<NeoRadioButton />` (Oruga [Radio](https://oruga.io/components/radio.html)) #5976 
- [x] `<b-autocomplete />` => `<NeoAutocomplete />` (Oruga [Autocomplete](https://oruga.io/components/autocomplete.html)) #6018 
- [x] `<b-loading />` => `<NeoLoading />` (Oruga [Loading](https://oruga.io/components/Loading.html)) #5933
- [x] `<b-tooltip />` => #5856 
- [x] `<b-message />` => notification or Bulma [message](https://bulma.io/documentation/components/message/) - 3 results #6068
- [x] `<b-image />` => `<img />` #5854
- [x] `<b-field />` => `<NeoField />` #5870 
- [x] `<b-input />` => `<NeoInput />` #5870
- [x] `<b-tag />` => `<NeoTag />` check Bulma [Tag](https://bulma.io/documentation/elements/tag/) - 3 results #6155 
- [x] `<b-table />` => `<NeoTable />` (Oruga [Table](https://oruga.io/components/Table.html)) - 8 results (related with #6110, #6144)
- [x] `<b-table-columns />` => `<NeoTableColumn />` - 87 results (related with #6110, #6144)
- [x] `<b-numberinput />` => `<NeoInput />` type=number??  - 3 results #6195 
- [x] `<b-taginput />` => `<NeoInputitems />` - 1 result #6183 
- [x] `<b-collapse />` => `<NeoCollapse />` (Oruga [Collapse](https://oruga.io/components/Collapse.html)) -  <s>13</s> 10 results #6249
- [x] `<b-dropdown />` => `<NeoDropdown />` - 3 results #6196
- [x] `<b-dropdown-item />` => `<NeoDropdownItem />` - 26 results #6196
- [x] `<b-slider />` => `<NeoSlider />` Oruga [slider](https://oruga.io/components/slider.html) - #6340
- [x] `<b-upload />` => `<NeoUpload />` Oruga [upload](https://oruga.io/components/upload.html) - #6341
- [x] `<b-pagination />` => `<NeoPagination />` Oruga [Pagination](https://oruga.io/components/pagination.html) #6366 
- [x] `<b-tabs />` => `<NeoTabs />` (Oruga [Tabs](https://oruga.io/components/Tabs.html))  - 9 results #6231 
- [x] `<b-tab-item />` => `<NeoTabItem />` -  15 results #6231 
- [x] `<b-navbar />` => [Bulma Navbar](https://bulma.io/documentation/components/navbar/) #6382 
- [x] `<b-navbar-item />` => custom html ??? #6382 
- [x] `<b-select />` => `<NeoSelect />` - 15 results #6200, #6338
- [x] `<b-button />` => `<NeoButton />` - <s>64</s> <s>47</s> <s>41</s> 35 results (make it the last one) #6437 #6449 
- [x] #6277 

lmk if you want to work on a specific component.

**Comment by prachi00** [comment]
@roiLeo 
I'll do 

- [ ] <b-icon /> => <NeoIcon />

**Comment by prachi00** [comment]
I'll do this now:
`

- [ ]  <b-input /> => <NeoInput />

`

**Comment by prachi00** [comment]
@roiLeo we also use <b-autocomplete which isnt mentioned in description

**Comment by emagici** [comment]
@roiLeo 
I will handle  it.
[ ]  <b-checkbox /> => <NeoCheckbox />

**Comment by Gavin-Gong** [comment]
I will handle `b-modal` component
- [ ] `<b-modal />` => `<NeoModal />`

**Comment by prachi00** [comment]
I'll also do <b-field to neofield as I need that in <neoinput 

- [ ] `<b-field /> => <NeoField />`

**Comment by prachi00** [comment]
Also doing this now:

- [ ] `<b-modal /> => <NeoModal />`

**Comment by prachi00** [comment]
changing <b-button to <neobutton would change the ui of buttons everywhere, are we okay with that? @roiLeo

**Comment by roiLeo** [comment]
> changing <b-button to <neobutton would change the ui of buttons everywhere, are we okay with that?

Nope, we sould keep UI how it is maybe try to create new variant?

**Comment by preschian** [comment]
will check on `<b-steps />` and `<b-steps-item />`

**Comment by preschian** [comment]
will check on `b-switch, b-datepicker, and b-radio-button`

**Comment by roiLeo** [comment]
> edit: currently there is no equivalent of b-radio-button on oruga

https://oruga.io/components/Radio.html ?

**Comment by preschian** [comment]
> [oruga.io/components/Radio.html](https://oruga.io/components/Radio.html) ?

seems like Oruga only has `Radio`, but no variants for `RadioButton`. ref: https://buefy.org/documentation/radio#radio-button

but, let me follow buefy implementation. ref: https://github.com/buefy/buefy/blob/dev/src/components/radio/RadioButton.vue

**Comment by prachi00** [comment]
I'll do 

- [ ] `<b-autocomplete /> => <NeoAutocomplete />`

**Comment by prachi00** [comment]
I'll do 

- [ ] `<b-tag /> => <NeoTag />`

**Comment by prachi00** [comment]
@roiLeo are we also moving away from buefy class helpers then like is-flex and stuff

**Comment by prachi00** [comment]
@roiLeo are we still keeping bulma and its class helpers?

**Comment by roiLeo** [comment]
> @roiLeo are we still keeping bulma and its class helpers?

yes, we'll keep it for now

**Comment by brano-hozza** [comment]
i will do `<b-select />`

**Comment by preschian** [comment]
will check on `b-dropdown`

**Comment by prachi00** [comment]
@roiLeo for <b-numberinput, if we replace with <neoInput type number, Ui wont be same, it will be like this, is this okay? 
<img width="730" alt="Screen Shot 2023-06-07 at 9 17 40 PM" src="https://github.com/kodadot/nft-gallery/assets/39299315/5ff746eb-c0dd-427c-89b1-b77568c1a01e">
<img width="718" alt="Screen Shot 2023-06-07 at 9 17 50 PM" src="https://github.com/kodadot/nft-gallery/assets/39299315/5f5e3d1a-72cc-40b9-ab6a-4d3699d42dac">

**Comment by roiLeo** [comment]
> @roiLeo for <b-numberinput, if we replace with <neoInput type number, Ui wont be same, it will be like this, is this okay? <img alt="Screen Shot 2023-06-07 at 9 17 40 PM" width="730" src="https://user-images.githubusercontent.com/39299315/244262922-5ff746eb-c0dd-427c-89b1-b77568c1a01e.png"> <img alt="Screen Shot 2023-06-07 at 9 17 50 PM" width="718" src="https://user-images.githubusercontent.com/39299315/244262958-5f5e3d1a-72cc-40b9-ab6a-4d3699d42dac.png">

I find two possible solution:

1. replace numberinput with `<NeoInput type="number" />`
2. create new custom component with Grouped [fields](https://oruga.io/components/field.html)  (with + button on right and - on left)

both solutions work for me

**Comment by roiLeo** [comment]
Hey @brano-hozza just saw your oruga issue, I think this is stil doable with a workaround by adding `icon` prop to `o-select` component. And then you should be able to update class color.

![Screenshot 2023-06-09 at 10-53-05 KodaDot - NFT Market Explorer](https://github.com/kodadot/nft-gallery/assets/9987732/f7e7a14d-1207-4dff-82b1-c61fb5effb8b)

**Comment by preschian** [comment]
will check on `b-tabs` and `b-tab-item`

**Comment by preschian** [comment]
will check `b-collapse` also

**Comment by roiLeo** [comment]
For Programmatic stuff (modal, toast, notification..), I think we need to do some important changes in `libs/ui`:
- use vue3 (or nuxt check out histoire examples)
- replace `@histoire/plugin-vue2`
- import `@oruga-ui/oruga-next` 
- test components
- profit!

ref #5611

**Comment by yangwao** [comment]
Realistically we have it done all? Or are there some which might pop up?

**Comment by roiLeo** [comment]
> Realistically we have it done all? Or are there some which might pop up?

Notification, Modal, Snackbar & Toast

see https://github.com/kodadot/nft-gallery/pull/6610#issue-1839964503 we'll need to make a big bang (Vue3 => Nuxt3 => Oruga-next) to close this one

**Comment by preschian** [comment]
> Notification, Modal, Snackbar & Toast
> 
> see [#6610 (comment)](https://github.com/kodadot/nft-gallery/pull/6610#issue-1839964503) we'll need to make a big bang (Vue3 => Nuxt3 => Oruga-next) to close this one

I think we can make a separate issue for this

1. migrate Modal -> https://github.com/kodadot/nft-gallery/pull/6714
2. migrate Notification & Toast

and then, when we migrate to Nuxt3, we need to migrate to `oruga-next` also

3. migrate `oruga-next` -> https://github.com/kodadot/nft-gallery/pull/6610

we need to remove `buefy` first before we go to no.3
