### ISSUE TITLE
Basilisk v0.1

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#660]
More changes related to current BSX implementation coming soon in:
- [ ] https://github.com/kodadot/nft-gallery/issues/3376

### Explorer

- [ ] https://github.com/kodadot/nft-gallery/issues/2881

### Offers
- [ ] https://github.com/kodadot/nft-gallery/issues/3584
- [ ] https://github.com/kodadot/nft-gallery/issues/3583
- [ ] https://github.com/kodadot/nft-gallery/issues/3514
- [ ] https://github.com/kodadot/nft-gallery/issues/3401
- [ ] https://github.com/kodadot/nft-gallery/issues/766
- [ ] https://github.com/kodadot/nft-gallery/issues/3463

### Related Issues
- [ ] https://github.com/kodadot/nft-gallery/issues/3362
- [ ] https://github.com/kodadot/nft-gallery/issues/3291
- [ ] https://github.com/kodadot/nft-gallery/issues/3134
- [ ] https://github.com/kodadot/nft-gallery/issues/3138
- [ ] https://github.com/kodadot/nft-gallery/issues/3207
- [ ] https://github.com/kodadot/nft-gallery/issues/3265
- [ ] https://github.com/kodadot/nft-gallery/issues/3352
- [ ] https://github.com/kodadot/nft-gallery/issues/3350
- [ ] https://github.com/kodadot/nft-gallery/issues/3368
- [ ] https://github.com/kodadot/nft-gallery/issues/3294

### Auctions
- [ ] https://github.com/kodadot/nft-gallery/issues/2776

### Implemented
- [x] https://github.com/kodadot/nft-gallery/issues/3333
- [x] https://github.com/kodadot/nft-gallery/issues/3513
- [x] https://github.com/kodadot/nft-gallery/issues/3349
- [x] https://github.com/kodadot/nft-gallery/issues/3520
- [x] https://github.com/kodadot/nft-gallery/issues/3607
- [x] https://github.com/kodadot/nft-gallery/issues/3205
- [x] https://github.com/kodadot/nft-gallery/issues/3203
- [x] https://github.com/kodadot/nft-gallery/issues/3312
- [x] https://github.com/kodadot/nft-gallery/issues/3364
- [x] https://github.com/kodadot/nft-gallery/issues/3292
- [x] https://github.com/kodadot/nft-gallery/issues/3293
- [x] https://github.com/kodadot/nft-gallery/issues/3400
- [x] https://github.com/kodadot/nft-gallery/issues/3374
- [x] https://github.com/kodadot/nft-gallery/issues/1015
- [x] https://github.com/kodadot/nft-gallery/issues/2801
- [x] https://github.com/kodadot/nft-gallery/issues/3339
- [x] https://github.com/kodadot/nft-gallery/issues/3279
- [x] https://github.com/kodadot/nft-gallery/issues/3258
- [x] https://github.com/kodadot/nft-gallery/issues/3342
- [x] https://github.com/kodadot/nft-gallery/issues/3378
- [x] https://github.com/kodadot/nft-gallery/issues/3221
- [x] https://github.com/kodadot/nft-gallery/issues/3385
- [x] https://github.com/kodadot/nft-gallery/issues/3387
- [x] https://github.com/kodadot/nft-gallery/issues/3346
- [x] https://github.com/kodadot/nft-gallery/issues/3278
- [x] https://github.com/kodadot/nft-gallery/issues/3354
- [x] https://github.com/kodadot/nft-gallery/issues/3253
- [x] https://github.com/kodadot/nft-gallery/issues/3280
- [x] https://github.com/kodadot/nft-gallery/issues/3202
- [x] https://github.com/kodadot/nft-gallery/issues/3286
- [x] https://github.com/kodadot/nft-gallery/issues/3285
- [x] https://github.com/kodadot/nft-gallery/issues/3039
- [x] https://github.com/kodadot/nft-gallery/issues/3137
- [x] https://github.com/kodadot/nft-gallery/issues/3136
- [x] https://github.com/kodadot/nft-gallery/issues/3116
- [x] https://github.com/kodadot/nft-gallery/issues/3047
- [x] https://github.com/kodadot/nft-gallery/issues/3171
- [x] https://github.com/kodadot/nft-gallery/issues/3163
- [x] https://github.com/kodadot/nft-gallery/issues/3156
- [x] https://github.com/kodadot/nft-gallery/issues/3332

### Indexer:
- [x] Implement base nft subsquid indexer
- [x] Add ability to set price https://github.com/kodadot/snek/issues/10
- [x] Chance to add royalties https://github.com/kodadot/snek/issues/8
- [x] Possilibity to manage offers https://github.com/kodadot/snek/issues/9

### UI:
- [x]  Make a page dedicated to creating a unique (NFT) with a simple workflow
- [x]  Ability to create a Class (collection)
- [ ]  Show class detail with metadata
- [x]  Show minted NFTs in explorer mode
- [x]  Show user's profile
- [ ]  Display metadata for particular NFT (instance)
- [ ]  Burn an instance
- [ ]  Implement a page to teleport KSM between Kusama and Basiliskv
- [ ]  Extend [vue-polkadot/api](https://github.com/vue-polkadot/vue-ui/tree/master/packages/vue-api) to handle multiple (parallel connections).
- [ ]  Provide check if a user has enough balance on Basilisk / Kusama to be able to mint and transfer a collection.

### Marketplace
- [x] Buy
- [x] SetPrice
- [x] Make / Accept offer

#### Additionally, historical data should be displayed in a sensible manner:
- [ ] history of trades, offers, floor and ceiling prices
- [ ] statistics of the whole marketplace and individual classes

### Needs to be done for bounty
Submissions are open until June 20, 12 CET.
[Source](https://github.com/galacticcouncil/amsterdot-bounties-2022/issues/3)

- [x] Create a class
  - Creates a class, (i.e. collection) of tokens that can all be described by certain set of common properties.
- [x] Mint
  - Mints a token that is unique within a class.
- [x]  Transfer
  - Transfers ownership of a token to another wallet.
- [x] Burn
  - Destroys a previously minted token.
- [x] Destroy a class
  - Destroys a previously created class. In our implementation, such a class cannot contain any minted tokens inside.
  - https://github.com/kodadot/snek/issues/35
  - https://github.com/kodadot/nft-gallery/issues/3206
- [x] Set a price
  - Also commonly called a listing. Owner of a token can list their token on the marketplace with a specified price for which it can be bought instantly by other users.
- [x] Buy
  - A user can buy a listed token for previously set price by its owner.
- [x] Make an offer
  - Even if a user does not set price for their token, other users can make offers for which they would buy the token. This reserves a full offered amount on offerer's account. Only one offer can be made by one account for a token.
- [x] Withdraw an offer
  - Retract a previous offer and unreserve funds.
- [x] Accept an offer
  - Owner of a token can decide to accept an offer which then acts as a regular buy action.
- [x] Add a royalty
  - Owner of an NFT can embed a royalty to a token. That means from that point on, each trade of this NFT will split the full amount to the royaltee (usually the owner) and the seller of the NFT in the defined ratio.

**Comment by vikiival** [comment]
>  remove whole text from frontpage ambasador & github &c

Why ?

**Comment by XyloDrone** [comment]
How high priority is this and are the tasks the same :)

**Comment by vikiival** [comment]
> How high priority 

p1 for @vikiival

**Comment by yangwao** [comment]
What we are missing to make it run for testing?

**Comment by vikiival** [comment]
Things I had to make to make it running and can break stuff
- remove `max from `queries/fragments/collectionDetails.graphql`

**Comment by yangwao** [comment]
Let's push some version, others can help you out so we can make things faster:)

**Comment by vikiival** [comment]
Slightly rugged by #2975

**Comment by yangwao** [comment]
<img src="https://media4.giphy.com/media/iIYTP2Jz2wdhAEyZrn/giphy.gif"/>

**Comment by petersopko** [comment]
as discussed, I've moved the unfinished issues from this one into
- #3648 

since we're moving forward
