### ISSUE TITLE
Fix GraphQL calls in Nuxt3

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7225]
We need to review GraphQL calls on pages after migration. 
Could you write down which one you plan to fix? 
Make PR against `nuxt` branch.

top of my head
---
- collection view - https://nuxt.kodadot.xyz/ahk/collection/158
- Gallery item 
- Explorer items view - https://nuxt.kodadot.xyz/ahk/explore/items?listed=true
- create items - fetch existing collections
- sidebar calls for balances 
- profile items 
- profile collections
- profile activity
- search - navbar
- search - items from particular collection

Fix all GraphQL calls.
---
- page by page & components by components
- feel free add some which I've missed

**Comment by sivareddyuppathi** [comment]
👋

**Comment by kodabot** [comment]
ASSIGNED - @sivareddyuppathi 🔒 LOCKED -> Sunday, September 10th 2023, 20:32:44 UTC -> 24 hours

**Comment by kodabot** [comment]
ASSIGNMENT EXPIRED - @sivareddyuppathi has been unassigned.

**Comment by roiLeo** [comment]
#### Update

- [x] collection view
- [x] Gallery item (Missing `CarouselTypeVisited`)
- [x] Explorer items view 
- [x] create items - fetch existing collections (tested on bsx/snek missing rmrk)
- [x] sidebar calls for balances 
- [x] profile items 
- [x] profile collections
- [x] profile activity

#### TODO

- [ ] search - navbar
- [ ] search - items from particular collection
- [ ] Holders
- [ ] Sales
- [ ] Spotlight
- [ ] Identity Name?
- [ ] Mass Mint
- [ ] and more...

**Comment by roiLeo** [comment]
so far so good
