### ISSUE TITLE
Migration leftovers 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8293]
this will hopefully keep better track of todo things

https://github.com/kodadot/nft-gallery/issues/7552 describes how waiting for your action should work at the end
related PR open: https://github.com/kodadot/nft-gallery/pull/8201
- this pr is not valid

related to testing/burning: https://github.com/kodadot/nft-gallery/issues/7552#issuecomment-1824450795

_Originally posted by @prury 

## Tasks

- [ ] Not possible to migrate gets removed 
- [ ] waiting for your action to finish  #7560 
- [ ] testing https://github.com/kodadot/nft-gallery/issues/7552#issuecomment-1824450795

**Comment by yangwao** [comment]
Still important but not urgent.

**Comment by preschian** [comment]
maybe @hassnian wanna help with this one? https://github.com/kodadot/nft-gallery/issues/8563

**Comment by hassnian** [comment]
> maybe @hassnian wanna help with this one? https://github.com/kodadot/nft-gallery/issues/8563

sure will grab asap
