### ISSUE TITLE
Denver test drop issues

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9559]
https://canary.kodadot.xyz/ahk/drops/alteration

- [ ] ~~#9563~~ (Drop changed from free to paid)

- [ ] ~~problem specified in this issue still occurs: https://github.com/kodadot/nft-gallery/issues/9495~~ (Drop changed from free to paid)

- [x] #9566

- [ ] https://github.com/kodadot/nft-gallery/issues/9559#issuecomment-1968816404 (Problems found by daiagi)

- [x] https://github.com/kodadot/nft-gallery/issues/9559#issuecomment-1968954266 (IPFS upload error)

- [ ] https://github.com/kodadot/nft-gallery/issues/9559#issuecomment-1967787022 (Hopefully fixed by Arrowsquid)

- [ ] Time estimation not present on modal

**Comment by daiagi** [comment]
>even if i clear cache it does not reset modal state

Hi @prury 
can you give more deets?
how to reproduce?

**Comment by prury** [comment]
> > even if i clear cache it does not reset modal state
> 
> Hi @prury can you give more deets? how to reproduce?

whatever it was, was not able to reproduce it as well, will be watching

**Comment by prury** [comment]
@vikiival 
minted nft is not same as preview/generated: 

https://github.com/kodadot/nft-gallery/assets/36627808/beb84220-1661-4937-bf70-c9a87975f5b8

**Comment by vikiival** [comment]
Probably more cc @Jarsen136

**Comment by Jarsen136** [comment]
> @vikiival minted nft is not same as preview/generated:
> 
>  

It should be related to the process of updating nft metadata.

I have just made a test drop. In the beginning, the image was the default one but after a few minutes, it changed to the correct one.

the default one: bafybeiae4xhymicuzaczqvtislpg67kcjj2maiov24tkdywpwtgzxiwzfa

success result from api:

```
{
    "result": {
        "sn": 16,
        "collection": "396",
        "chain": "ahk",
        "txHash": {
            "ok": true,
            "versionstamp": "0100001c5e6966100000"
        },
        "id": 16,
        "name": "Alteration #16",
        "image": "ipfs://bafybeiem63feg6j66q5xemawqsqwcclcice2ddxamqcrd5blly2fuoekwi/?hash=0x95e967dcdf583fc7a04a194f51fd3785328d811d613e527e30add24f396273d9"
    }
}
```
<img width="658" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/e34efd2a-f0d0-4d7c-9f23-ff72fb237d27">

The image `ipfs://bafybeiem63feg6j66q5xemawqsqwcclcice2ddxamqcrd5blly2fuoekwi/?hash=0x95e967dcdf583fc7a04a194f51fd3785328d811d613e527e30add24f396273d9` is correct and the same as preview.

https://canary.kodadot.xyz/ahk/gallery/396-16

<img width="960" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/cce72fee-8352-476e-b6ed-3e5394adab71">

**Comment by daiagi** [comment]
issues encountered:

- [ ] can not take screenshot if trying to mint first variation (i.e. don't click "create new variation)
- [ ] once, got the toast saying can't mint more then once per address, however, nft was minted
- [ ] in the modal, during success and while waiting for "list nft" button to finish loading, nft image is usually empty
- [ ] page refreshes when closing modal, from #9453. it's not a great UX


@prury  any of these are already known?

**Comment by prury** [comment]
> issues encountered:
> 
>     * [ ]  can not take screenshot if trying to mint first variation (i.e. don't click "create new variation)
> 
>     * [ ]  once, got the toast saying can't mint more then once per address, however, nft was minted
> 
>     * [ ]  in the modal, during success and while waiting for "list nft" button to finish loading, nft image is usually empty
> 
>     * [ ]  page refreshes when closing modal, from [fix: When I mint and want mint again, mint button doesnot work #9453](https://github.com/kodadot/nft-gallery/pull/9453). it's not a great UX
> 
> 
> @prury any of these are already known?

nope, ty

**Comment by prury** [comment]
> > @vikiival minted nft is not same as preview/generated:
> 
> It should be related to the process of updating nft metadata.
> 
> I have just made a test drop. In the beginning, the image was the default one but after a few minutes, it changed to the correct one.
> 
> the default one: bafybeiae4xhymicuzaczqvtislpg67kcjj2maiov24tkdywpwtgzxiwzfa
> 
> success result from api:
> 
> ```
> {
>     "result": {
>         "sn": 16,
>         "collection": "396",
>         "chain": "ahk",
>         "txHash": {
>             "ok": true,
>             "versionstamp": "0100001c5e6966100000"
>         },
>         "id": 16,
>         "name": "Alteration #16",
>         "image": "ipfs://bafybeiem63feg6j66q5xemawqsqwcclcice2ddxamqcrd5blly2fuoekwi/?hash=0x95e967dcdf583fc7a04a194f51fd3785328d811d613e527e30add24f396273d9"
>     }
> }
> ```
> 
> <img alt="image" width="658" src="https://private-user-images.githubusercontent.com/31397967/308495477-e34efd2a-f0d0-4d7c-9f23-ff72fb237d27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjUzMjcsIm5iZiI6MTcwOTEyNTAyNywicGF0aCI6Ii8zMTM5Nzk2Ny8zMDg0OTU0NzctZTM0ZWZkMmEtZjBkMC00ZDdjLTlmMjMtZmY3MmZiMjM3ZDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEyNTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMTY1Nzc5OTBhNjI4NTAyYTBhZjg0NmI1NTJjZWNjZDg5MGQwMTZmYWYyNzNiOWNhMDJjYTY4ODUyMTFjM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N7R6klMY-5pW3wz56PhBWPUqt6dbP8n31i8DoEGQscc">
> 
> The image `ipfs://bafybeiem63feg6j66q5xemawqsqwcclcice2ddxamqcrd5blly2fuoekwi/?hash=0x95e967dcdf583fc7a04a194f51fd3785328d811d613e527e30add24f396273d9` is correct and the same as preview.
> 
> https://canary.kodadot.xyz/ahk/gallery/396-16
> <img alt="image" width="960" src="https://private-user-images.githubusercontent.com/31397967/308505116-cce72fee-8352-476e-b6ed-3e5394adab71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjUzMjcsIm5iZiI6MTcwOTEyNTAyNywicGF0aCI6Ii8zMTM5Nzk2Ny8zMDg1MDUxMTYtY2NlNzJmZWUtODM1Mi00NzZlLWI2ZWQtM2U1Mzk0YWRhYjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEyNTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiOWNlNTgzYzE5N2FkYWU0MzhhODNhY2NmNDVkMjIxZjA0Mzc3NTEzOWVmNjg0MDU2YmI3MTY2YTY1NWM2ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SLxmOogm-RH8g6HzGGU_K2e0cyfKOG0jc4N6SXyJlwg">

![image](https://github.com/kodadot/nft-gallery/assets/36627808/f7bb3db3-ac20-4c8a-b12c-5b8e3ec1999d)

**Comment by prury** [comment]
still happening:
![image](https://github.com/kodadot/nft-gallery/assets/36627808/093ff962-b367-45af-90ba-638e33390264)

**Comment by prury** [comment]
- [ ] time estimation not present when minting paid drop

**Comment by vikiival** [comment]
> in the modal, during success and while waiting for "list nft" button to finish loading, nft image is usually empty

Backend only returns the stuff you send to it. So i would check if the corect data goes to the backend or propably it is an issue with image service

**Comment by vikiival** [comment]
> the one i minted yesterday still didn't change:  Alteration 15
> 
> 
> 
> also 18 and 19 are the same as it


You can always check if the bot minted it correctly. 

https://assethub-kusama.subscan.io/account/15CoYMEnJhhWHvdEPXDuTBnZKXwrJzMQdcMwcHGsVx5kXYvW

**Comment by prury** [comment]
> 
> You can always check if the bot minted it correctly.
> 

oh thanks, I've checked and indeed, images from the bot are correct
only problem is koda not reflecting real image then

**Comment by vikiival** [comment]
> only problem is koda not reflecting real image then

Lol let's do the test deploy then

**Comment by vikiival** [comment]
OOK this is issue from subsquid

![Screenshot 2024-02-28 at 14 06 23](https://github.com/kodadot/nft-gallery/assets/22471030/fffdf85d-bfda-437e-a525-c80ea4378594)

**Comment by preschian** [comment]
Is it safe to close?

**Comment by prury** [comment]
> Is it safe to close?

i believe so, closing, thank you.
